//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessFileSrvRef.IProcessFileToDBSrv")]
    public interface IProcessFileToDBSrv {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación UploadFile no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFileToDBSrv/UploadFile", ReplyAction="http://tempuri.org/IProcessFileToDBSrv/UploadFileResponse")]
        LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.UploadFileResponse UploadFile(LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFileToDBSrv/UploadFile", ReplyAction="http://tempuri.org/IProcessFileToDBSrv/UploadFileResponse")]
        System.Threading.Tasks.Task<LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.UploadFileResponse> UploadFileAsync(LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Filename;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string Filename, long Length, System.IO.Stream FileByteStream) {
            this.Filename = Filename;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessFileToDBSrvChannel : LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessFileToDBSrvClient : System.ServiceModel.ClientBase<LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv>, LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv {
        
        public ProcessFileToDBSrvClient() {
        }
        
        public ProcessFileToDBSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessFileToDBSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessFileToDBSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessFileToDBSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.UploadFileResponse LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv.UploadFile(LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string Filename, long Length, System.IO.Stream FileByteStream) {
            LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo inValue = new LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo();
            inValue.Filename = Filename;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.UploadFileResponse retVal = ((LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.UploadFileResponse> LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv.UploadFileAsync(LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.UploadFileResponse> UploadFileAsync(string Filename, long Length, System.IO.Stream FileByteStream) {
            LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo inValue = new LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.RemoteFileInfo();
            inValue.Filename = Filename;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((LoadFileToDb.WinForm.TestUI.ProcessFileSrvRef.IProcessFileToDBSrv)(this)).UploadFileAsync(inValue);
        }
    }
}
